#############################################################################
# Makefile for building: build/arias.app/Contents/MacOS/arias
# Generated by qmake (2.01a) (Qt 4.6.3) on: Thu Jul 8 16:45:39 2010
# Project:  arias.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile arias.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch i386 -arch ppc -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch i386 -arch ppc -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtOpenGL.framework/Versions/4/Headers -I/usr/include/QtOpenGL -I/usr/include -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -Ibuild -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386 -arch ppc
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtOpenGL -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = DoubleDelegate.cpp \
		Grid.cpp \
		HeaderDialog.cpp \
		ImageCanvas.cpp \
		InspectorCanvas.cpp \
		main.cpp \
		MainWindow.cpp \
		Patch.cpp \
		Processor.cpp \
		stat.cpp build/moc_DoubleDelegate.cpp \
		build/moc_HeaderDialog.cpp \
		build/moc_ImageCanvas.cpp \
		build/moc_InspectorCanvas.cpp \
		build/moc_MainWindow.cpp \
		build/moc_Processor.cpp \
		qrc_resources.cpp
OBJECTS       = build/DoubleDelegate.o \
		build/Grid.o \
		build/HeaderDialog.o \
		build/ImageCanvas.o \
		build/InspectorCanvas.o \
		build/main.o \
		build/MainWindow.o \
		build/Patch.o \
		build/Processor.o \
		build/stat.o \
		build/moc_DoubleDelegate.o \
		build/moc_HeaderDialog.o \
		build/moc_ImageCanvas.o \
		build/moc_InspectorCanvas.o \
		build/moc_MainWindow.o \
		build/moc_Processor.o \
		build/qrc_resources.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		arias.pro.conf \
		/usr/local/Qt4.6/mkspecs/features/release.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		arias.pro
QMAKE_TARGET  = arias
DESTDIR       = build/
TARGET        = build/arias.app/Contents/MacOS/arias

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		i386 \
		-arch \
		ppc \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build/arias.app/Contents/PkgInfo build/arias.app/Contents/Resources/empty.lproj build/arias.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_HeaderDialog.h ui_MainWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/arias.app/Contents/MacOS/ || $(MKDIR) build/arias.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: arias.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		arias.pro.conf \
		/usr/local/Qt4.6/mkspecs/features/release.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile arias.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
arias.pro.conf:
/usr/local/Qt4.6/mkspecs/features/release.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/mac/ppc.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/opengl.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile arias.pro

build/arias.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) build/arias.app/Contents || $(MKDIR) build/arias.app/Contents 
	@$(DEL_FILE) build/arias.app/Contents/PkgInfo
	@echo "APPL????" >build/arias.app/Contents/PkgInfo
build/arias.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) build/arias.app/Contents/Resources || $(MKDIR) build/arias.app/Contents/Resources 
	@touch build/arias.app/Contents/Resources/empty.lproj
	
build/arias.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) build/arias.app/Contents || $(MKDIR) build/arias.app/Contents 
	@$(DEL_FILE) build/arias.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,arias,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >build/arias.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) build/arias1.0.0 || $(MKDIR) build/arias1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/arias1.0.0/ && $(COPY_FILE) --parents DoubleDelegate.h Grid.h HeaderDialog.h ImageCanvas.h InspectorCanvas.h MainWindow.h Matrix.h Patch.h Processor.h stat.h build/arias1.0.0/ && $(COPY_FILE) --parents resources.qrc build/arias1.0.0/ && $(COPY_FILE) --parents DoubleDelegate.cpp Grid.cpp HeaderDialog.cpp ImageCanvas.cpp InspectorCanvas.cpp main.cpp MainWindow.cpp Patch.cpp Processor.cpp stat.cpp build/arias1.0.0/ && $(COPY_FILE) --parents HeaderDialog.ui MainWindow.ui build/arias1.0.0/ && (cd `dirname build/arias1.0.0` && $(TAR) arias1.0.0.tar arias1.0.0 && $(COMPRESS) arias1.0.0.tar) && $(MOVE) `dirname build/arias1.0.0`/arias1.0.0.tar.gz . && $(DEL_FILE) -r build/arias1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r build/arias.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: build/moc_DoubleDelegate.cpp build/moc_HeaderDialog.cpp build/moc_ImageCanvas.cpp build/moc_InspectorCanvas.cpp build/moc_MainWindow.cpp build/moc_Processor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_DoubleDelegate.cpp build/moc_HeaderDialog.cpp build/moc_ImageCanvas.cpp build/moc_InspectorCanvas.cpp build/moc_MainWindow.cpp build/moc_Processor.cpp
build/moc_DoubleDelegate.cpp: DoubleDelegate.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ DoubleDelegate.h -o build/moc_DoubleDelegate.cpp

build/moc_HeaderDialog.cpp: ui_HeaderDialog.h \
		HeaderDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ HeaderDialog.h -o build/moc_HeaderDialog.cpp

build/moc_ImageCanvas.cpp: Grid.h \
		Patch.h \
		ImageCanvas.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ImageCanvas.h -o build/moc_ImageCanvas.cpp

build/moc_InspectorCanvas.cpp: Matrix.h \
		Processor.h \
		Patch.h \
		Grid.h \
		InspectorCanvas.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ InspectorCanvas.h -o build/moc_InspectorCanvas.cpp

build/moc_MainWindow.cpp: ui_MainWindow.h \
		Processor.h \
		Matrix.h \
		Patch.h \
		Grid.h \
		MainWindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MainWindow.h -o build/moc_MainWindow.cpp

build/moc_Processor.cpp: Matrix.h \
		Patch.h \
		Grid.h \
		Processor.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Processor.h -o build/moc_Processor.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		pic/toggle-mask.png \
		pic/load-project.png \
		pic/save-project.png \
		pic/apply-mask.png \
		pic/open-image.png \
		pic/reset-view.png \
		pic/calculate-average.png
	/Developer/Tools/Qt/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_HeaderDialog.h ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_HeaderDialog.h ui_MainWindow.h
ui_HeaderDialog.h: HeaderDialog.ui
	/Developer/Tools/Qt/uic HeaderDialog.ui -o ui_HeaderDialog.h

ui_MainWindow.h: MainWindow.ui \
		InspectorCanvas.h \
		ImageCanvas.h \
		Matrix.h \
		Processor.h \
		Patch.h \
		Grid.h \
		Grid.h \
		Patch.h
	/Developer/Tools/Qt/uic MainWindow.ui -o ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/DoubleDelegate.o: DoubleDelegate.cpp DoubleDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/DoubleDelegate.o DoubleDelegate.cpp

build/Grid.o: Grid.cpp Grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Grid.o Grid.cpp

build/HeaderDialog.o: HeaderDialog.cpp HeaderDialog.h \
		ui_HeaderDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/HeaderDialog.o HeaderDialog.cpp

build/ImageCanvas.o: ImageCanvas.cpp ImageCanvas.h \
		Grid.h \
		Patch.h \
		Processor.h \
		Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ImageCanvas.o ImageCanvas.cpp

build/InspectorCanvas.o: InspectorCanvas.cpp InspectorCanvas.h \
		Matrix.h \
		Processor.h \
		Patch.h \
		Grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/InspectorCanvas.o InspectorCanvas.cpp

build/main.o: main.cpp MainWindow.h \
		ui_MainWindow.h \
		Processor.h \
		Matrix.h \
		Patch.h \
		Grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainWindow.h \
		Processor.h \
		Matrix.h \
		Patch.h \
		Grid.h \
		HeaderDialog.h \
		ui_HeaderDialog.h \
		DoubleDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o MainWindow.cpp

build/Patch.o: Patch.cpp Patch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Patch.o Patch.cpp

build/Processor.o: Processor.cpp Processor.h \
		Matrix.h \
		Patch.h \
		Grid.h \
		stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Processor.o Processor.cpp

build/stat.o: stat.cpp stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/stat.o stat.cpp

build/moc_DoubleDelegate.o: build/moc_DoubleDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_DoubleDelegate.o build/moc_DoubleDelegate.cpp

build/moc_HeaderDialog.o: build/moc_HeaderDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_HeaderDialog.o build/moc_HeaderDialog.cpp

build/moc_ImageCanvas.o: build/moc_ImageCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ImageCanvas.o build/moc_ImageCanvas.cpp

build/moc_InspectorCanvas.o: build/moc_InspectorCanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_InspectorCanvas.o build/moc_InspectorCanvas.cpp

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

build/moc_Processor.o: build/moc_Processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Processor.o build/moc_Processor.cpp

build/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

